### ISSUE TITLE
Is there a way to specify the font family?

### ISSUE THREAD

**Issue by bertradio** [arminveres/md-pdf.nvim#13]
I like sans serif fonts. An option to set the font family would be useful.

Thanks

**Comment by arminveres** [comment]
Hi there, that's a fair point and valid use-case. I will open a PR for it as soon as I am able to, thanks!

**Comment by arminveres** [comment]
@bertradio you should be now able to change your font and pass custom arguments if necessary, enjoy!

**Comment by bertradio** [comment]
Thanks. But when I add the code in the README I get this error:

**Comment by arminveres** [comment]
@bertradio can you provide the exact snippet you used? TIA

**Comment by bertradio** [comment]
No matter what I try and convert I get the same result.

Here is a simple test file that generates the error I sent.

**Comment by bertradio** [comment]
-- markdown-pdf.lua
--
-- Makes pdf from md file and displays in Okular
--
-- Created: 05/10/24

My_map('n', '<Leader>,', function() require("md-pdf").convert_md_to_pdf() end, { desc = 'Markdown pdf preview' })

return {
'arminveres/md-pdf.nvim',
branch = 'main', -- you can assume that main is somewhat stable until releases will be made
opts = {
-- no table of contents
toc = false,
-- set code highlighting
highlight = 'pygments',
-- Specify font, `nil` uses the default font of the theme
-- fonts = nil,
-- or, where all or only some options can be specified. NOTE: those that are `nil` can be left
-- out completely
fonts = {
main_font = nil,
sans_font = "DejaVuSans",
mono_font = "IosevkaTerm Nerd Font Mono",
math_font = nil,
},
-- Custom options passed to `pandoc` CLI call, can be ignored for setup
pandoc_user_args = nil,
-- or
-- pandoc_user_args = {
-- -- short
-- "-V KEY[:VALUE]",
-- -- long options
-- "--standalone=false",
-- },
},
}

**Comment by arminveres** [comment]
@bertradio Yeah the issue seems to be with you copying all the examples, while they are duplicating, see comments, to show the different ways to set them up.
Try this:
```lua

{
    'arminveres/md-pdf.nvim',
    keys = {
        {
            "<leader>,",
            function() require("md-pdf").convert_md_to_pdf() end,
            desc = "Markdown preview",
        },
    },
    opts = {
        fonts = {
            main_fonts = "DejaVuSans" -- or whatever you prefer
        }
    },
}
```

Also try to add the exact error you were getting, otherwise it's hard for me to debug.

**Comment by bertradio** [comment]
Here's what I have:
return {

'arminveres/md-pdf.nvim',
keys = { { "<leader>,", function() require("md-pdf").convert_md_to_pdf() end, desc = "Markdown preview", }, },
opts = {
fonts = { main_fonts = "DejaVuSans" -- or whatever you prefer_width
}
},

}

And this is the nvim error

**Comment by arminveres** [comment]
You still did not provide the error.

**Comment by bertradio** [comment]
I had put it in the email as an inline image. Attached is the file.

**Comment by arminveres** [comment]
I can honestly not see any attachment. Can you copy the text or paste the image into GitHub?

**Comment by bertradio** [comment]
Here's the error I'm getting:

md-pdf: Error producing PDF.
! Font \TU/lmr/m/n/10=[lmroman10-regular:+tlig; at 10pt not loadable: metric data not found or bad
<to be read again>
relax
1.112 ...lt\familydefault\seriesdefault\shapedefault

I am running Nvim 0.10 (latest release version) under Linux Debian 12 on a Chromebook via the Crostini VM.

**Comment by arminveres** [comment]
That looks like a font error coming from pandoc itself; try different fonts or try finding the correct name. Good luck!
