### ISSUE TITLE
error: nvim_echo must not be called in a lua loop callback

### ISSUE THREAD

**Issue by avsej** [arminveres/md-pdf.nvim#8]
I've configured using defaults from readme. 
Neovim version: https://github.com/neovim/neovim/commit/beca82721

```
Error executing luv callback:                                                                                                                                                                              
vim/_editor.lua:0: E5560: nvim_echo must not be called in a lua loop callback
stack traceback:
        [C]: in function 'nvim_echo'
        vim/_editor.lua: in function 'notify'
        .../site/pack/packer/start/md-pdf.nvim/lua/md-pdf/utils.lua:17: in function 'log_info'
        ...m/site/pack/packer/start/md-pdf.nvim/lua/md-pdf/init.lua:61: in function 'print_out'
        ...m/site/pack/packer/start/md-pdf.nvim/lua/md-pdf/init.lua:108: in function <...m/site/pack/packer/start/md-pdf.nvim/lua/md-pdf/init.lua:98>
```

**Comment by arminveres** [comment]
Hi, that's weird, I am on nightly and I have not encountered this error.
Did you build Neovim from scratch on that commit?
Could you post your `nvim --version`?

**Comment by powerblo** [comment]
Hey, I've encountered the same error, here's my nvim version.

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by vlimki** [comment]
Same error here.

**Comment by arminveres** [comment]
Since I am unable to reproduce, I can not really fix it properly, but I created a branch and would ask you to try to pin it to that, then I'd know if it's fixed! add the following line to the lazy setup:
```lua
branch = "fix/echo-loop"
```

**Comment by vlimki** [comment]
Hey, thanks for the quick response! Unfortunately, it did not fix it for me.

I tried to do some inspection myself and commenting out the line in utils.lua:
```lua
function M.log_info(str)
    -- vim.notify(str)
end
```
fixed it for me. Works great now! Not sure what's happening under the hood, but this is the error I get when the line is not commented out:
![image](https://github.com/arminveres/md-pdf.nvim/assets/155232924/094dbc09-0cce-4b30-a96f-434dc8ba80ec)

**Comment by arminveres** [comment]
Hi there, I updated, force pushed, to the `fix/echo-loop` branch, could someone check, if the issue persists?
I wrapped the `vim.notify` call into a `pcall` therefore if there is an error, it is suppressed.
@vlimki @avsej @powerblo

**Comment by brennenputh** [comment]
Just attempted the fix/echo-loop branch, chiming in to say that the fix works perfectly for me.

**Comment by powerblo** [comment]
fix/echo-loop works well with nvim v0.10.0. Thanks a lot!

**Comment by matovu-farid** [comment]
I still faced the same issue. I am on nvim v0.10.0.

**Comment by tjaartvdwalt** [comment]
fix/echo-loop branch fixes the problem for me as well.
